version: "3.2"

services:

  database:
    container_name: database
    image: mongo:3.0
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  server:
    container_name: server
    build:
      context: ./server
    depends_on:
      - database
    ports:
      - "3000:3000"
