version: "3"

services:

  database:
    container_name: database
    image: mongo:3.0
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  frontend:
    container_name: frontend
    build:
      context: ./client
    depends_on:
      - server
    ports:
      - "8080:8080"
      - "8181:8181"
      - "80:80"

  server:
    container_name: server
    build:
      context: ./server
    depends_on:
      - database
    ports:
      - "3000:3000"
